# Generated by Django 5.2.2 on 2025-06-18 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_profile_bio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='bio',
        ),
    ]
