# Generated by Django 5.2.2 on 2025-06-26 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0009_remove_post_picture_postprofilecontent_post_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='postprofilecontent',
            name='content_type',
            field=models.CharField(choices=[('image', 'Image'), ('video', 'Video')], default='image', max_length=10),
        ),
    ]
